
export const racingData = [
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: 3,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			},
			{
				image: 'images/chicken-thumbnail.png',
				lane: 5,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			},
			{
				image: 'images/chicken-thumbnail.png',
				lane: 8,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	}
];

export const scheduledRacingData = [
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: 3,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			},
			{
				image: 'images/chicken-thumbnail.png',
				lane: 5,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			},
			{
				image: 'images/chicken-thumbnail.png',
				lane: 8,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	}
];


export const resultsRacingData = [
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		winner: 'Chicken',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: 3,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			},
			{
				image: 'images/chicken-thumbnail.png',
				lane: 5,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			},
			{
				image: 'images/chicken-thumbnail.png',
				lane: 8,
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		winner: 'Chicken',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		winner: 'Chicken',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	},
	{
		event: 'Juvinile Jubile',
		location: 'US San Francisco',
		winner: 'Chicken',
		peckingOrder: 'A',
		distance: 1600,
		terrain: '',
		entryFee: '5.99',
		prizePool: '5.99',
		capacity: 8,
		startIn: 102,
		racingChickens: [
			{
				image: 'images/chicken-thumbnail.png',
				lane: '',
				name: 'Willber',
				heritage: 'Dorking',
				perfection: '96',
				owner: 'John',
				history: '2/0/4',
				races: 12,
				stock: 'Stock',
				talent: 'Talent',
				class: 'A',
				pop: 12,
				winnings: 5.99,
				situations: 'race pen',
				gender: 'Roaster',
				color: 'orange',
				stripes: 'Stripes',
				eyes: 'Eyes',
				beak: 'Beak',
				comb: 'Red',
				wattle: 'Red',
				Background: 'Background'
			}
		]
	}
];
